"""Report service - Generate reports and PDFs"""

from typing import Dict, Any
from io import BytesIO
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle
from reportlab.lib import colors
from datetime import datetime


class ReportService:
    """Service for generating reports and PDFs"""

    @staticmethod
    def generate_pdf_report(report_data: Dict[str, Any]) -> BytesIO:
        """Generate PDF report from analysis data"""
        buffer = BytesIO()
        
        # Create PDF
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=0.75*inch,
            leftMargin=0.75*inch,
            topMargin=0.75*inch,
            bottomMargin=0.75*inch
        )

        # Container for elements
        elements = []
        styles = getSampleStyleSheet()
        
        # Title
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#2563eb'),
            spaceAfter=30,
            alignment=1  # Center
        )
        elements.append(Paragraph("DecisionLens AI Clarity Report", title_style))
        elements.append(Spacer(1, 0.3*inch))

        # Decision Summary
        elements.append(Paragraph("Decision Summary", styles['Heading2']))
        elements.append(Paragraph(report_data.get('decision_title', 'Untitled'), styles['Normal']))
        elements.append(Spacer(1, 0.2*inch))

        # Key Insights
        elements.append(Paragraph("Key Insights", styles['Heading2']))
        for insight in report_data.get('key_insights', []):
            elements.append(Paragraph(f"• {insight}", styles['Normal']))
        elements.append(Spacer(1, 0.2*inch))

        # Ranked Priorities
        elements.append(Paragraph("Ranked Priorities", styles['Heading2']))
        for i, priority in enumerate(report_data.get('ranked_priorities', []), 1):
            elements.append(Paragraph(f"{i}. {priority}", styles['Normal']))
        elements.append(Spacer(1, 0.2*inch))

        # Core Tradeoffs
        elements.append(Paragraph("Core Tradeoffs", styles['Heading2']))
        for tradeoff in report_data.get('core_tradeoffs', []):
            elements.append(Paragraph(f"• {tradeoff}", styles['Normal']))
        elements.append(Spacer(1, 0.2*inch))

        # Missing Information
        elements.append(Paragraph("Missing Information", styles['Heading2']))
        for info in report_data.get('missing_information', []):
            elements.append(Paragraph(f"• {info}", styles['Normal']))
        elements.append(PageBreak())

        # Next Research Steps
        elements.append(Paragraph("Next Research Steps", styles['Heading2']))
        for i, step in enumerate(report_data.get('next_research_steps', []), 1):
            elements.append(Paragraph(f"{i}. {step}", styles['Normal']))
        elements.append(Spacer(1, 0.2*inch))

        # Decision Framework
        elements.append(Paragraph("Decision Framework", styles['Heading2']))
        elements.append(Paragraph(report_data.get('decision_framework', ''), styles['Normal']))
        elements.append(Spacer(1, 0.2*inch))

        # Gut Check Questions
        elements.append(Paragraph("Gut Check Questions", styles['Heading2']))
        for question in report_data.get('gut_check_questions', []):
            elements.append(Paragraph(f"• {question}", styles['Normal']))
        elements.append(Spacer(1, 0.3*inch))

        # Footer
        footer_text = f"Generated by DecisionLens AI on {datetime.now().strftime('%B %d, %Y at %I:%M %p')}"
        elements.append(Paragraph(footer_text, styles['Normal']))

        # Build PDF
        doc.build(elements)
        buffer.seek(0)
        return buffer
